In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv('sonar.csv')

In [4]:
data=pd.DataFrame(data=data)

In [5]:
data

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

     0.0090  0.0032  R  
0    0.0052  0.0044  R  
1    0.0095  0.0078  R  
2    0.0040  0.0117  R  
3    0.0107  0.0094  R  
4    0.0051  0.0062  R  
..      ...     ... ..  
202  0.0193  0.0157  M  
203  0.0062  0.0067  M  
204  0.0077  0.0031  M  
205  0.0036  0.0048  M  
206  0.0061  0.0115  M  

[207 rows x 61 columns]

In [6]:
x=data.iloc[:,0:-1]
pca=PCA(n_components=10)

In [7]:
y=data.iloc[:,-1]

In [8]:
xpca=pca.fit_transform(x)
x=xpca

In [9]:
pd.DataFrame(data=x)

0         1         2         3         4         5         6  \
0   -0.970285  1.017654  0.830432  0.120147  0.299120  0.202682 -0.226988   
1   -0.324435  0.876876  0.228203  0.868926  0.098053 -0.269122 -0.421778   
2    0.853571  0.697734 -0.023602 -0.123425 -0.584388  0.351808  0.478187   
3   -0.061337  0.226034  0.635198  0.152907  0.150982  0.081111 -0.374523   
4   -0.605423  0.901962  0.804550  0.271896  0.496832  0.464410 -0.224909   
..        ...       ...       ...       ...       ...       ...       ...   
202  0.049918 -1.028980  0.265634  0.026018 -0.014738  0.097506  0.012021   
203  0.228374 -1.149870  0.200437  0.043461  0.182020  0.010158  0.084858   
204  0.306763 -1.147756  0.248975 -0.058557  0.161337  0.013778  0.049391   
205 -0.038083 -0.994049  0.201938 -0.060790 -0.147673 -0.088874  0.018656   
206 -0.043904 -0.910802  0.009169 -0.045577 -0.030723 -0.033778  0.025213   

            7         8         9  
0    0.384837  0.004329 -0.082679  
1    0.081072  0.014185 -0.432334  
2   -0.215424 -0.533955 -0.425182  
3    0.070143  0.119454 -0.427480  
4    0.105504 -0.202842 -0.235048  
..        ...       ...       ...  
202  0.178998  0.029362 -0.268631  
203  0.266152 -0.068963 -0.307679  
204  0.227866 -0.070132 -0.313294  
205  0.069504 -0.024406 -0.165303  
206 -0.019100  0.120130 -0.137964  

[207 rows x 10 columns]

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scale=StandardScaler()

In [13]:
x=scale.fit_transform(x)

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [17]:
lr=LogisticRegression()

In [18]:
lr.fit(x_train,y_train)

LogisticRegression()

In [20]:
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))      

0.8043478260869565
[[23  1]
 [ 8 14]]
              precision    recall  f1-score   support

           M       0.74      0.96      0.84        24
           R       0.93      0.64      0.76        22

    accuracy                           0.80        46
   macro avg       0.84      0.80      0.80        46
weighted avg       0.83      0.80      0.80        46



In [21]:
gnb=GaussianNB()

In [22]:
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))   

0.782608695652174
[[21  3]
 [ 7 15]]
              precision    recall  f1-score   support

           M       0.75      0.88      0.81        24
           R       0.83      0.68      0.75        22

    accuracy                           0.78        46
   macro avg       0.79      0.78      0.78        46
weighted avg       0.79      0.78      0.78        46



In [23]:
svc=SVC()

In [24]:
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))   

0.8913043478260869
[[23  1]
 [ 4 18]]
              precision    recall  f1-score   support

           M       0.85      0.96      0.90        24
           R       0.95      0.82      0.88        22

    accuracy                           0.89        46
   macro avg       0.90      0.89      0.89        46
weighted avg       0.90      0.89      0.89        46



In [25]:
dt=DecisionTreeClassifier()

In [26]:
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))   

0.6956521739130435
[[18  6]
 [ 8 14]]
              precision    recall  f1-score   support

           M       0.69      0.75      0.72        24
           R       0.70      0.64      0.67        22

    accuracy                           0.70        46
   macro avg       0.70      0.69      0.69        46
weighted avg       0.70      0.70      0.69        46



# Cross Validation

In [28]:
from sklearn.model_selection import cross_val_score
gnbscores=cross_val_score(gnb,x,y,cv=5)
print(gnbscores)
print(gnbscores.mean(),gnbscores.std())

[0.42857143 0.73809524 0.43902439 0.73170732 0.3902439 ]
0.5455284552845528 0.15548626224792733


In [29]:
from sklearn.model_selection import cross_val_score
svcscores=cross_val_score(svc,x,y,cv=5)
print(svcscores)
print(svcscores.mean(),svcscores.std())

[0.45238095 0.76190476 0.51219512 0.75609756 0.3902439 ]
0.5745644599303136 0.15546283624706844


In [30]:
from sklearn.model_selection import cross_val_score
dtscores=cross_val_score(dt,x,y,cv=5)
print(dtscores)
print(dtscores.mean(),dtscores.std())

[0.69047619 0.61904762 0.46341463 0.68292683 0.53658537]
0.5984901277584205 0.08728251974516124
